Name: Tests

on:
  - push
  - pull_requests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      martix:
        os:[ubuntu-latest, windows-latest]
      python-version: ['3.6', '3.9', '3.12']
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip install tox tox-gh-actions
    - name: Test with tox
      run: tox  